/** Shared with tracking notifications, partner SMS, crew portal, and checkpoint API. */
export type TrackingStatus =
  | "not_started"
  | "en_route_to_pickup"
  | "arrived_at_pickup"
  | "inventory_check"
  | "loading"
  | "wrapping"
  | "en_route_to_destination"
  | "en_route_venue"
  | "arrived_at_destination"
  | "arrived_venue"
  | "unloading"
  | "unloading_setup"
  | "event_active"
  | "teardown"
  | "loading_return"
  | "en_route_return"
  | "unloading_return"
  | "unwrapping_placement"
  | "walkthrough_photos"
  | "working"
  | "delivering_bins"
  | "collecting_bins"
  | "completed"
  | "en_route"
  | "arrived"
  | "delivering";
