/**
 * Generate the editorial Invoice PDF for a single move and hand back
 * a signed download URL. Bypasses the completion-status guard on the
 * HTTP endpoint so operators can produce a proper invoice for a
 * Confirmed move that has a signed contract but has not been serviced
 * yet (event bookings, deposits paid awaiting service).
 *
 * The Move Summary + Receipt PDFs get co-generated by generateMovePDFs
 * — normal on a completed move, but for a not-yet-serviced move the
 * receipt values reflect only the deposit-so-far state. The invoice is
 * the deliverable; the other two overwrite themselves on real
 * completion.
 *
 * Usage:
 *   npx tsx scripts/generate-invoice-single-move.ts MV-30377
 */
import { config } from "dotenv";
import { resolve } from "path";

config({ path: resolve(process.cwd(), ".env.local") });

async function main() {
  const code = (process.argv[2] || "").trim().toUpperCase();
  if (!code) {
    console.error("pass a move code, e.g. MV-30377");
    process.exit(1);
  }

  const { createAdminClient } = await import("@/lib/supabase/admin");
  const { generateMovePDFs } = await import("@/lib/documents/generateMovePDFs");

  const admin = createAdminClient();
  const { data: move, error } = await admin
    .from("moves")
    .select("id, move_code, client_name, status, estimate, amount")
    .eq("move_code", code)
    .maybeSingle();
  if (error || !move) {
    console.error("move not found:", code);
    process.exit(1);
  }

  console.log(`generating invoice for ${move.move_code} (${move.client_name}, status=${move.status})...`);

  const paths = await generateMovePDFs(move.id);
  console.log("  invoice path :", paths.invoicePath);
  console.log("  summary path :", paths.summaryPath);
  console.log("  receipt path :", paths.receiptPath);

  const { data: signed, error: signErr } = await admin.storage
    .from("move-documents")
    .createSignedUrl(paths.invoicePath, 60 * 60 * 24 * 7);

  if (signErr || !signed) {
    console.error("could not sign URL:", signErr?.message);
    process.exit(1);
  }

  console.log("\ninvoice download URL (7-day signed):");
  console.log(signed.signedUrl);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
