#!/usr/bin/env node
// Regenerates docs/typography-audit.md from src TS and TSX files.
// Run: node scripts/typography-audit.mjs
import fs from "fs";
import path from "path";

const ROOT = path.join(process.cwd(), "src");
const OUT = path.join(process.cwd(), "docs", "typography-audit.md");

const patternPx = /([a-z0-9-]*:)*text-\[(\d+)px\]/g;
const patternVar = /text-\[var\(--(text-[a-z0-9-]+)\)\]/g;
const patternTw = /\btext-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl)\b/g;

function walk(dir, acc = []) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) walk(p, acc);
    else if (/\.(tsx|ts)$/.test(name)) acc.push(p);
  }
  return acc;
}

function firstMatch(files, regex) {
  const seen = new Map();
  for (const file of files) {
    const text = fs.readFileSync(file, "utf8");
    const lines = text.split("\n");
    lines.forEach((line, i) => {
      let m;
      const r = new RegExp(regex.source, regex.flags);
      while ((m = r.exec(line)) !== null) {
        const key = m[1] ?? m[0];
        if (!seen.has(key)) seen.set(key, { file: path.relative(process.cwd(), file), line: i + 1, snippet: line.trim().slice(0, 140) });
      }
    });
  }
  return seen;
}

const files = walk(ROOT);

const pxExamples = new Map();
for (const file of files) {
  const lines = fs.readFileSync(file, "utf8").split("\n");
  lines.forEach((line, i) => {
    let m;
    const r = new RegExp(patternPx.source, patternPx.flags);
    while ((m = r.exec(line)) !== null) {
      const size = `${m[2]}px`;
      if (!pxExamples.has(size)) {
        const full = m[0];
        pxExamples.set(size, { file: path.relative(process.cwd(), file), line: i + 1, cls: full, snippet: line.trim().slice(0, 130) });
      }
    }
  });
}

const varExamples = new Map();
for (const file of files) {
  const lines = fs.readFileSync(file, "utf8").split("\n");
  lines.forEach((line, i) => {
    let m;
    const r = new RegExp(patternVar.source, patternVar.flags);
    while ((m = r.exec(line)) !== null) {
      const key = m[1];
      if (!varExamples.has(key)) varExamples.set(key, { file: path.relative(process.cwd(), file), line: i + 1, snippet: line.trim().slice(0, 130) });
    }
  });
}

const twOrder = ["xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl"];
const twExamples = new Map();
for (const file of files) {
  const lines = fs.readFileSync(file, "utf8").split("\n");
  lines.forEach((line, i) => {
    // Avoid matching `text-base` inside `text-[var(--text-base)]`
    const stripped = line.replace(/text-\[var\(--[^)]+\)\]/g, "");
    let m;
    const r = new RegExp(patternTw.source, patternTw.flags);
    while ((m = r.exec(stripped)) !== null) {
      const key = m[1];
      if (!twExamples.has(key)) twExamples.set(key, { file: path.relative(process.cwd(), file), line: i + 1, snippet: line.trim().slice(0, 130) });
    }
  });
}

const sizes = [...pxExamples.keys()].sort((a, b) => parseInt(a, 10) - parseInt(b, 10));

let md = `<!-- AUTO-GENERATED by scripts/typography-audit.mjs — do not edit by hand -->

# Typography audit (yugo-ops)

Generated from a scan of \`src/**/*.ts\` and \`src/**/*.tsx\`. Re-run:

\`\`\`bash
node scripts/typography-audit.mjs
\`\`\`

## 1. Design tokens (\`:root\` in \`src/app/globals.css\`)

| Token | Size | Intended use (comment in CSS) |
|-------|------|------------------------------|
| \`--text-xs\` | 11px | micro: timestamps, dense badges (not primary reading) |
| \`--text-sm\` | 12px | secondary labels, metadata |
| \`--text-base\` | 16px | body, primary list/table text |
| \`--text-md\` | 18px | emphasized body, intros |
| \`--text-lg\` | 20px | card / section titles (heading-sm) |
| \`--text-xl\` | 22px | section headings |
| \`--text-2xl\` | 26px | metrics, large stats |
| \`--text-3xl\` | 32px | page titles |
| \`--text-hero\` | 40px | hero / marketing headlines |

**Base document:** \`body\` uses \`font-size: 16px\` in \`globals.css\` (components override with classes).

## 2. Semantic CSS classes (\`globals.css\` — \`.ty-*\`)

These map to the tokens above; grep shows **little or no** \`.tsx\` usage yet — prefer them for new UI to reduce \`text-[Npx]\` sprawl.

| Class | Token / size | Role |
|-------|----------------|------|
| \`.ty-caption\` | \`--text-xs\` | timestamps, micro text |
| \`.ty-label\` | \`--text-sm\` | form labels, column headers |
| \`.ty-label-upper\` | \`--text-xs\` upper | section headers |
| \`.ty-body\` | \`--text-base\` | body |
| \`.ty-body-medium\` | \`--text-base\` medium | emphasized body |
| \`.ty-body-lg\` | \`--text-md\` | descriptions |
| \`.ty-heading-sm\` | \`--text-lg\` | card titles |
| \`.ty-heading\` | \`--text-xl\` | section headings |
| \`.ty-metric\` | \`--text-2xl\` | dashboard numbers |
| \`.ty-page-title\` | \`--text-3xl\` | page titles |

## 3. CSS variable text sizing in TSX (e.g. \`text-[var(--text-base)]\`)

| Token | File:line | Snippet |
|-------|-----------|---------|
`;

for (const k of [...varExamples.keys()].sort()) {
  const ex = varExamples.get(k);
  const sn = ex.snippet.replace(/\|/g, "\\|").replace(/`/g, "'");
  md += `| \`${k}\` | \`${ex.file}:${ex.line}\` | \`${sn}\` |\n`;
}
if (varExamples.size === 0) md += "| — | — | _None found._ |\n";

md += `
## 4. Tailwind scale (\`text-xs\` … \`text-4xl\`) — first occurrence in TSX

| Class | Tailwind default (v4) | First example |
|-------|------------------------|---------------|
`;

const twDefaults = {
  xs: "0.75rem (12px)",
  sm: "0.875rem (14px)",
  base: "1rem (16px)",
  lg: "1.125rem (18px)",
  xl: "1.25rem (20px)",
  "2xl": "1.5rem (24px)",
  "3xl": "1.875rem (30px)",
  "4xl": "2.25rem (36px)",
};

for (const k of twOrder) {
  const ex = twExamples.get(k);
  if (ex) {
    md += `| \`text-${k}\` | ${twDefaults[k] || "see Tailwind"} | \`${ex.file}:${ex.line}\` |\n`;
  }
}
md += "\n_Not used in TSX:_ ";
md += twOrder.filter((k) => !twExamples.has(k)).map((k) => `\`text-${k}\``).join(", ") || "—";
md += "\n\n## 5. Arbitrary pixel classes \`text-[Npx]\` — one example each\n\n";
md += `| Size | Example class (first hit) | File:line |\n|------|---------------------------|------------|\n`;
for (const s of sizes) {
  const ex = pxExamples.get(s);
  md += `| ${s} | \`${ex.cls}\` | \`${ex.file}:${ex.line}\` |\n`;
}

md += `
## 6. Other notable fixed sizes in \`globals.css\`

Legacy / component classes: \`.mc-l\` (11px), \`.mc-v\` (\`var(--text-2xl)\`), \`.dc-t\` (\`var(--text-base)\`), \`.bdg\` (11px), \`.admin-view-all-link\` (12px), \`.btn\` (0.875rem), mapbox/popup rules, etc. See repo-wide search for \`font-size:\`.

## 7. One-line examples (tokens and semantic classes)

Use **either** arbitrary sizes like \`text-[var(--text-base)]\` / \`text-[var(--text-md)]\` (see \`ActivityPageClient\`) **or** semantic \`.ty-caption\`, \`.ty-body\`, etc. (bundles size + weight + color in \`globals.css\`).

| Token | Size | Arbitrary value example | Semantic class example |
|-------|------|-------------------------|-------------------------|
| \`--text-xs\` | 11px | \`className="text-[var(--text-xs)] text-[var(--tx3)]"\` | \`className="ty-caption"\` |
| \`--text-sm\` | 12px | \`className="text-[var(--text-sm)]"\` | \`className="ty-label"\` |
| \`--text-base\` | 16px | \`className="text-[var(--text-base)] text-[var(--tx)]"\` | \`className="ty-body"\` |
| \`--text-md\` | 18px | \`className="text-[var(--text-md)] text-[var(--tx3)]"\` | \`className="ty-body-lg"\` |
| \`--text-lg\` | 20px | \`className="text-[var(--text-lg)] font-heading font-bold"\` | \`className="ty-heading-sm"\` |
| \`--text-xl\` | 22px | \`className="text-[var(--text-xl)] font-heading font-bold"\` | \`className="ty-heading"\` |
| \`--text-2xl\` | 26px | \`className="text-[var(--text-2xl)] font-heading font-bold"\` | \`className="ty-metric"\` |
| \`--text-3xl\` | 32px | \`className="text-[var(--text-3xl)] font-heading font-bold"\` | \`className="ty-page-title"\` |
| \`--text-hero\` | 40px | \`className="text-[var(--text-hero)] font-hero"\` | _(no \`.ty-*\` — use token or custom)_ |

Tailwind’s \`text-sm\` / \`text-base\` / … use **rem** sizes that differ from these tokens; first TSX hits are listed in §4.

---
_Total unique \`text-[Npx]\` sizes in TS/TSX: **${sizes.length}**._
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, md);
console.log(`Wrote ${OUT}`);
