import type { Contact } from "./contacts-table-with-modal.types"

export const defaultContacts: Contact[] = [
  {
    id: "1",
    name: "Pierre from Claap",
    email: "pierre@claap.io",
    connectionStrength: "Weak",
    twitterFollowers: 2400,
    description: "Tech entrepreneur and investor",
  },
  {
    id: "2",
    name: "HardwareSavvy",
    email: "hardwaresavvy+andr...",
    connectionStrength: "Very strong",
    twitterFollowers: 8900,
    description: "Hardware specialist",
  },
  {
    id: "3",
    name: "Voiceform",
    email: "harrison@voiceform.c...",
    connectionStrength: "Good",
    twitterFollowers: 5200,
    description: "Voice technology expert",
  },
  {
    id: "4",
    name: "Marketer Milk",
    email: "hi@marketmilk.com",
    connectionStrength: "Good",
    twitterFollowers: 6100,
    description: "Marketing strategist",
  },
  {
    id: "5",
    name: "Allen from CAST AI",
    email: "allen@mail.cast.ai",
    connectionStrength: "Weak",
    twitterFollowers: 3300,
    description: "AI infrastructure lead",
  },
  {
    id: "6",
    name: "Marija Krasnovskytė",
    email: "marija@cast.ai",
    connectionStrength: "Very weak",
    twitterFollowers: 1800,
    description: "Technical advisor",
  },
  {
    id: "7",
    name: "eryn@basistheory.com",
    email: "eryn@basistheory.com",
    connectionStrength: "Very weak",
    twitterFollowers: 2100,
    description: "Security specialist",
  },
  {
    id: "8",
    name: "Brad Patterson",
    email: "brad@basistheory.com",
    connectionStrength: "Good",
    twitterFollowers: 4500,
    description: "Product manager",
  },
  {
    id: "9",
    name: "Sarah Chen",
    email: "sarah.chen@techvault.com",
    connectionStrength: "Very strong",
    twitterFollowers: 12400,
    description: "CEO and founder",
  },
  {
    id: "10",
    name: "David Rodriguez",
    email: "david.rodriguez@innovate.io",
    connectionStrength: "Good",
    twitterFollowers: 7800,
    description: "Lead developer",
  },
  {
    id: "11",
    name: "Emily Watson",
    email: "emily.watson@future.co",
    connectionStrength: "Weak",
    twitterFollowers: 3900,
    description: "Marketing director",
  },
  {
    id: "12",
    name: "James Mitchell",
    email: "james@buildit.dev",
    connectionStrength: "Very strong",
    twitterFollowers: 9200,
    description: "Architect and advisor",
  },
  {
    id: "13",
    name: "Lisa Anderson",
    email: "lisa.anderson@ventures.com",
    connectionStrength: "Good",
    twitterFollowers: 5600,
    description: "Venture investor",
  },
  {
    id: "14",
    name: "Michael Zhang",
    email: "michael@cloudtech.ai",
    connectionStrength: "Weak",
    twitterFollowers: 4100,
    description: "Infrastructure engineer",
  },
  {
    id: "15",
    name: "Jennifer Lee",
    email: "jen@designsystem.io",
    connectionStrength: "Very strong",
    twitterFollowers: 11200,
    description: "Design system lead",
  },
  {
    id: "16",
    name: "Robert Chang",
    email: "robert.chang@quantify.co",
    connectionStrength: "Good",
    twitterFollowers: 6800,
    description: "Analytics expert",
  },
  {
    id: "17",
    name: "Amanda Pierce",
    email: "amanda@growthlab.com",
    connectionStrength: "Weak",
    twitterFollowers: 2900,
    description: "Growth consultant",
  },
  {
    id: "18",
    name: "Christopher Hayes",
    email: "chris.hayes@webscale.io",
    connectionStrength: "Very strong",
    twitterFollowers: 13500,
    description: "Platform engineer",
  },
  {
    id: "19",
    name: "Victoria Moore",
    email: "victoria@datasync.com",
    connectionStrength: "Good",
    twitterFollowers: 7100,
    description: "Data scientist",
  },
  {
    id: "20",
    name: "Nicholas Brown",
    email: "nick@apibase.dev",
    connectionStrength: "Very weak",
    twitterFollowers: 1500,
    description: "API developer",
  },
  {
    id: "21",
    name: "Rebecca Sullivan",
    email: "rebecca.s@innovationlab.io",
    connectionStrength: "Good",
    twitterFollowers: 8300,
    description: "Innovation strategist",
  },
  {
    id: "22",
    name: "Thomas Wright",
    email: "thomas@blockchain.tech",
    connectionStrength: "Weak",
    twitterFollowers: 3700,
    description: "Blockchain developer",
  },
  {
    id: "23",
    name: "Maria Garcia",
    email: "maria.garcia@futuretech.com",
    connectionStrength: "Very strong",
    twitterFollowers: 10800,
    description: "Tech evangelist",
  },
  {
    id: "24",
    name: "Daniel Park",
    email: "daniel@smartsolutions.ai",
    connectionStrength: "Good",
    twitterFollowers: 6400,
    description: "Solutions architect",
  },
  {
    id: "25",
    name: "Sophie Laurent",
    email: "sophie.laurent@design.co",
    connectionStrength: "Weak",
    twitterFollowers: 4200,
    description: "UX lead",
  },
]
